### ISSUE TITLE
Support for open id authentication and ldap authorization in a single request ?

### ISSUE THREAD

**Issue by megarajan** [criteo/haproxy-spoe-auth#11]
can we do first authentication via open id and authorization via ldap for a single http request using this library ?

**Comment by megarajan** [comment]
It would be great if someone can clarify my query ?

**Comment by clems4ever** [comment]
Hello, this app only handle one of OIDC or LDAP in one single request but not both at the same time. Handling both would mean resolving a conflict in the Authorization header with one providing a Bearer and the other one providing Basic.
