### ISSUE TITLE
Retrieve OIDC username as session variable

### ISSUE THREAD

**Issue by mildis** [criteo/haproxy-spoe-auth#16]
This would be nice to get the `preferred_username` OIDC claim inside a spoe variable back to haproxy.  
We could then set a request header `X-Auth-Username` to be used by the backends as a header authentication.

`preferred_username` could be configurable so another claim (maybe `email` or `sub`) would be returned to haproxy to identify the authenticated user.

**Comment by mougams** [comment]
https://github.com/criteo/haproxy-spoe-auth/releases/tag/v1.8.0 has been released.
