### ISSUE TITLE
LDAPs?

### ISSUE THREAD

**Issue by frankerooney** [criteo/haproxy-spoe-auth#2]
Hi. This works well with haproxy; thank you. I needed to amend the unauthorized backend a bit to make it work but it is good. 
Haproxy is in our DMZ so I would like to use LDAPs against our directory - but I can't figure how to form the ldap url or port to use ldaps, perhaps it isn't supported?
Thanks
Andy

**Comment by clems4ever** [comment]
Hello @frankerooney , if your ldap server is configured with TLS you can simply provide the ldaps:// schema in the LDAP URL provided as an argument to the agent and it should work. If it does not please report the problem here.
